'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Producto
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="inventarioProductos", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class inventarioProductos
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodProductField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        Private CantExistenceField As Integer
        
        Private CantReOrdenField As Integer
        
        Private SalePriceField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CodProduct() As String
            Get
                Return Me.CodProductField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodProductField, value) <> true) Then
                    Me.CodProductField = value
                    Me.RaisePropertyChanged("CodProduct")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property CantExistence() As Integer
            Get
                Return Me.CantExistenceField
            End Get
            Set
                If (Me.CantExistenceField.Equals(value) <> true) Then
                    Me.CantExistenceField = value
                    Me.RaisePropertyChanged("CantExistence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property CantReOrden() As Integer
            Get
                Return Me.CantReOrdenField
            End Get
            Set
                If (Me.CantReOrdenField.Equals(value) <> true) Then
                    Me.CantReOrdenField = value
                    Me.RaisePropertyChanged("CantReOrden")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property SalePrice() As Decimal
            Get
                Return Me.SalePriceField
            End Get
            Set
                If (Me.SalePriceField.Equals(value) <> true) Then
                    Me.SalePriceField = value
                    Me.RaisePropertyChanged("SalePrice")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Producto.ProductoSoap")>  _
    Public Interface ProductoSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codProduct del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Feature", ReplyAction:="*")>  _
        Function Feature(ByVal request As Producto.FeatureRequest) As Producto.FeatureResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Feature", ReplyAction:="*")>  _
        Function FeatureAsync(ByVal request As Producto.FeatureRequest) As System.Threading.Tasks.Task(Of Producto.FeatureResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class FeatureRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Feature", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Producto.FeatureRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Producto.FeatureRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FeatureRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public codProduct As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal codProduct As String)
            MyBase.New
            Me.codProduct = codProduct
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class FeatureResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FeatureResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Producto.FeatureResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Producto.FeatureResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FeatureResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public FeatureResult As Producto.inventarioProductos
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FeatureResult As Producto.inventarioProductos)
            MyBase.New
            Me.FeatureResult = FeatureResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ProductoSoapChannel
        Inherits Producto.ProductoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ProductoSoapClient
        Inherits System.ServiceModel.ClientBase(Of Producto.ProductoSoap)
        Implements Producto.ProductoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Producto_ProductoSoap_Feature(ByVal request As Producto.FeatureRequest) As Producto.FeatureResponse Implements Producto.ProductoSoap.Feature
            Return MyBase.Channel.Feature(request)
        End Function
        
        Public Function Feature(ByVal codProduct As String) As Producto.inventarioProductos
            Dim inValue As Producto.FeatureRequest = New Producto.FeatureRequest()
            inValue.Body = New Producto.FeatureRequestBody()
            inValue.Body.codProduct = codProduct
            Dim retVal As Producto.FeatureResponse = CType(Me,Producto.ProductoSoap).Feature(inValue)
            Return retVal.Body.FeatureResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Producto_ProductoSoap_FeatureAsync(ByVal request As Producto.FeatureRequest) As System.Threading.Tasks.Task(Of Producto.FeatureResponse) Implements Producto.ProductoSoap.FeatureAsync
            Return MyBase.Channel.FeatureAsync(request)
        End Function
        
        Public Function FeatureAsync(ByVal codProduct As String) As System.Threading.Tasks.Task(Of Producto.FeatureResponse)
            Dim inValue As Producto.FeatureRequest = New Producto.FeatureRequest()
            inValue.Body = New Producto.FeatureRequestBody()
            inValue.Body.codProduct = codProduct
            Return CType(Me,Producto.ProductoSoap).FeatureAsync(inValue)
        End Function
    End Class
End Namespace
